localPlanner:
  ros__parameters:
    pathFolder: "paths"
    vehicleLength: 0.6
    vehicleWidth: 0.6
    sensorOffsetX: 0.0  # 这些值可以根据需要进行修改
    sensorOffsetY: 0.0
    twoWayDrive: true
    laserVoxelSize: 0.05
    terrainVoxelSize: 0.2
    useTerrainAnalysis: false
    checkObstacle: true
    checkRotObstacle: false
    adjacentRange: 3.5
    obstacleHeightThre: 0.15
    groundHeightThre: 0.1
    costHeightThre: 0.1
    costScore: 0.02
    useCost: false
    pointPerPathThre: 2
    minRelZ: -0.5
    maxRelZ: 0.25
    maxSpeed: 1.0
    dirWeight: 0.02
    dirThre: 90.0
    dirToVehicle: false
    pathScale: 1.0
    minPathScale: 0.75
    pathScaleStep: 0.25
    pathScaleBySpeed: true
    minPathRange: 1.0
    pathRangeStep: 0.5
    pathRangeBySpeed: true
    pathCropByGoal: true
    autonomyMode: false
    autonomySpeed: 1.0
    joyToSpeedDelay: 2.0
    joyToCheckObstacleDelay: 5.0
    goalClearRange: 0.5
    goalX: 0.0
    goalY: 0.0


pathFollower:
  ros__parameters:
    sensorOffsetX: 0.0
    sensorOffsetY: 0.0
    pubSkipNum: 1
    twoWayDrive: true
    lookAheadDis: 0.5
    yawRateGain: 7.5
    stopYawRateGain: 7.5
    maxYawRate: 45.0
    maxSpeed: 1.0
    maxAccel: 1.0
    switchTimeThre: 1.0
    dirDiffThre: 0.1
    stopDisThre: 0.2
    slowDwnDisThre: 1.0
    useInclRateToSlow: false
    inclRateThre: 120.0
    slowRate1: 0.25
    slowRate2: 0.5
    slowTime1: 2.0
    slowTime2: 2.0
    useInclToStop: false
    inclThre: 45.0
    stopTime: 5.0
    noRotAtStop: false
    noRotAtGoal: true
    autonomyMode: false
    autonomySpeed: 1.0
    joyToSpeedDelay: 2.0